version: '3'
services:
  pg-dev:
    image: microsoft/mssql-server-linux
    hostname: mssql
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - skynet
networks:
  skynet:
