version: '3'
services:
  pg-dev:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    networks:
      - skynet
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=root"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8081:80"
    networks:
      - skynet
networks:
  skynet:
